<a href="https://colab.research.google.com/github/Team-Boost/Team_mission/blob/main/week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1번

In [2]:
import numpy as np

In [15]:
arr1=np.random.rand(5,3)
arr2=np.random.rand(3,2)
dot=arr1@arr2

In [16]:
print(dot,dot.shape)

[[0.28375316 0.31989323]
 [0.53489004 1.13684866]
 [0.52462553 0.91522315]
 [0.58632776 0.98239437]
 [0.84506826 0.80370101]] (5, 2)


2번

In [17]:
arr1=np.array([[5,7],[9,11]], float)
arr2=np.array([[2,4],[6,8]], float)

In [19]:
concat_1= np.concatenate((arr1,arr2),axis=0)
concat_2= np.concatenate((arr1,arr2),axis=1)

In [21]:
print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


3번

In [35]:
xy=np.array([[1., 2. ,3. ,4. ,5. ,6.],
            [10., 20., 30., 40., 50., 60.]])

x_train=xy[0]
y_train=xy[1]

In [36]:
print(x_train,x_train.shape)
print(y_train,y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


4번

In [40]:
beta_gd=np.random.rand(1)
bias=np.random.rand(1)

In [41]:
print(beta_gd,bias)

[0.98027486] [0.93517116]


5번

In [55]:
xy=np.array([[1., 2. ,3. ,4. ,5. ,6.],
            [3., 6., 9., 12., 15., 18.]])

In [64]:
x_train=xy[0]
y_train=xy[1]
beta_gd=np.random.rand(1)
bias=np.random.rand(1)
learning_rate=0.01

for i in range(1000):
  prediction=(beta_gd*x_train)+bias
  error=((prediction-y_train)**2).mean()
  gd_w=((prediction-y_train)*2*x_train).mean()
  gd_b=((prediction-y_train)*2).mean()

  beta_gd = beta_gd-learning_rate*gd_w
  bias = bias-learning_rate*gd_b

  if i % 100 ==0 :
    print('Epoch ({:10d}/1000) error: {:10f}, beta_gd:{:10f}, bias:{:10f}'.format(i,error,beta_gd.item(),bias.item()))

Epoch (         0/1000) error:  70.018981, beta_gd:  1.303950, bias:  1.016702
Epoch (       100/1000) error:   0.167469, beta_gd:  2.782889, bias:  0.929494
Epoch (       200/1000) error:   0.080606, beta_gd:  2.849375, bias:  0.644857
Epoch (       300/1000) error:   0.038797, beta_gd:  2.895500, bias:  0.447384
Epoch (       400/1000) error:   0.018674, beta_gd:  2.927501, bias:  0.310383
Epoch (       500/1000) error:   0.008988, beta_gd:  2.949702, bias:  0.215335
Epoch (       600/1000) error:   0.004326, beta_gd:  2.965105, bias:  0.149393
Epoch (       700/1000) error:   0.002082, beta_gd:  2.975791, bias:  0.103645
Epoch (       800/1000) error:   0.001002, beta_gd:  2.983204, bias:  0.071906
Epoch (       900/1000) error:   0.000482, beta_gd:  2.988348, bias:  0.049886
